export const dropdownStatus = [
  {
    label: "Tất cả",
    value: "",
  },
  {
    label: "Đã hoàn thành",
    value: "done",
  },
  {
    label: "Đã sửa",
    value: "edited",
  },
  {
    label: "Đã hủy",
    value: "canceled",
  },
];

export const listCODocuments = [
  {
    year: 2023,
    month: 1,
    quantity: 1459,
    key: "done",
    category: "Đã hoàn thành",
  },
  {
    year: 2023,
    month: 2,
    quantity: 1283,
    key: "done",
    category: "Đã hoàn thành",
  },
  {
    year: 2023,
    month: 3,
    quantity: 300,
    key: "done",
    category: "Đã hoàn thành",
  },
  {
    year: 2023,
    month: 4,
    quantity: 1829,
    key: "done",
    category: "Đã hoàn thành",
  },
  {
    year: 2023,
    month: 5,
    quantity: 2000,
    key: "done",
    category: "Đã hoàn thành",
  },
  {
    year: 2023,
    month: 6,
    quantity: 2100,
    key: "done",
    category: "Đã hoàn thành",
  },
  {
    year: 2023,
    month: 7,
    quantity: 1239,
    key: "done",
    category: "Đã hoàn thành",
  },
  {
    year: 2023,
    month: 8,
    quantity: 1690,
    key: "done",
    category: "Đã hoàn thành",
  },
  {
    year: 2023,
    month: 9,
    quantity: 1800,
    key: "done",
    category: "Đã hoàn thành",
  },
  {
    year: 2023,
    month: 10,
    quantity: 1900,
    key: "done",
    category: "Đã hoàn thành",
  },
  {
    year: 2023,
    month: 11,
    quantity: 2000,
    key: "done",
    category: "Đã hoàn thành",
  },
  {
    year: 2023,
    month: 12,
    quantity: 1600,
    key: "done",
    category: "Đã hoàn thành",
  },

  {
    year: 2023,
    month: 1,
    quantity: 1231,
    key: "edited",
    category: "Đã sửa",
  },
  {
    year: 2023,
    month: 2,
    quantity: 1000,
    key: "edited",
    category: "Đã sửa",
  },
  {
    year: 2023,
    month: 3,
    quantity: 890,
    key: "edited",
    category: "Đã sửa",
  },
  {
    year: 2023,
    month: 4,
    quantity: 457,
    key: "edited",
    category: "Đã sửa",
  },
  {
    year: 2023,
    month: 5,
    quantity: 700,
    key: "edited",
    category: "Đã sửa",
  },
  {
    year: 2023,
    month: 6,
    quantity: 789,
    key: "edited",
    category: "Đã sửa",
  },
  {
    year: 2023,
    month: 8,
    quantity: 435,
    key: "edited",
    category: "Đã sửa",
  },
  {
    year: 2023,
    month: 9,
    quantity: 1256,
    key: "edited",
    category: "Đã sửa",
  },
  {
    year: 2023,
    month: 10,
    quantity: 987,
    key: "edited",
    category: "Đã sửa",
  },
  {
    year: 2023,
    month: 11,
    quantity: 987,
    key: "edited",
    category: "Đã sửa",
  },
  {
    year: 2023,
    month: 12,
    quantity: 1987,
    key: "edited",
    category: "Đã sửa",
  },

  {
    year: 2023,
    month: 1,
    quantity: 100,
    key: "canceled",
    category: "Đã hủy",
  },
  {
    year: 2023,
    month: 2,
    quantity: 200,
    key: "canceled",
    category: "Đã hủy",
  },
  {
    year: 2023,
    month: 3,
    quantity: 500,
    key: "canceled",
    category: "Đã hủy",
  },
  {
    year: 2023,
    month: 4,
    quantity: 300,
    key: "canceled",
    category: "Đã hủy",
  },
  {
    year: 2023,
    month: 5,
    quantity: 100,
    key: "canceled",
    category: "Đã hủy",
  },
  {
    year: 2023,
    month: 6,
    quantity: 200,
    key: "canceled",
    category: "Đã hủy",
  },
  {
    year: 2023,
    month: 7,
    quantity: 389,
    key: "canceled",
    category: "Đã hủy",
  },
  {
    year: 2023,
    month: 8,
    quantity: 1244,
    key: "canceled",
    category: "Đã hủy",
  },
  {
    year: 2023,
    month: 9,
    quantity: 567,
    key: "canceled",
    category: "Đã hủy",
  },
  {
    year: 2023,
    month: 10,
    quantity: 100,
    key: "canceled",
    category: "Đã hủy",
  },
  {
    year: 2023,
    month: 11,
    quantity: 343,
    key: "canceled",
    category: "Đã hủy",
  },
  {
    year: 2023,
    month: 12,
    quantity: 1244,
    key: "canceled",
    category: "Đã hủy",
  },
];

export const color = {
  listThree: ["#008816", "#F4AA3A", "#FF4D4F"],
  listTwo: ["#008816", "#FF4D4F"],
  listColors: {
    done: "#008816",
    edited: "#F4AA3A",
    canceled: "#FF4D4F",
  },
};
