export const listDeclaration = [
  {
    declaration_num: "104469028310",
    date: "2022/10/1",
    cd_type: "E13",
    thread: "Vàng",
    bill: "311221CULVSHA2119959",
    bill_number: "R20211226001",
    shipping_terms: "CIF",
    gw: "65,066.13",
    pk: "928.0",
    import_or_export: "Nhập",
    mode_of_transport: "SEA",
    branch: "1",
    truck_type: "Cont40",
    truck_number: 5,
    factory_code: "ireier",
    dsk_person: null,
    check_person: null,
    note: "",
    fee: [
      {
        fee_id: "PHI01",
        fee_name: "Kiểm tra chất lượng đèn của bộ Khoa học Công nghệ",
        quantity: 1,
        unit_price: 13500000,
      },
      {
        fee_id: "PHI02",
        fee_name: "Test hiệu suất năng lượng",
        quantity: 1,
        unit_price: 5000000,
      },
    ],
  },
  {
    declaration_num: "10446902831",
    date: "2022/10/1",
    cd_type: "E13",
    thread: "Vàng",
    bill: "311221CULVSHA2119959",
    bill_number: "R20211226001",
    shipping_terms: "CIF",
    gw: "65,066.13",
    pk: "928.0",
    import_or_export: "Nhập",
    mode_of_transport: "SEA",
    branch: "1",
    truck_type: "Cont40",
    truck_number: 5,
    factory_code: "ireier",
    dsk_person: null,
    check_person: "Nguyễn Văn A",
    note: "",
    fee: [
      {
        fee_id: "PHI01",
        fee_name: "Kiểm tra chất lượng đèn của bộ Khoa học Công nghệ",
        quantity: 1,
        unit_price: 13500000,
      },
      {
        fee_id: "PHI02",
        fee_name: "Test hiệu suất năng lượng",
        quantity: 1,
        unit_price: 5000000,
      },
    ],
  },
  {
    declaration_num: "10446902830",
    date: "2022/10/1",
    cd_type: "E13",
    thread: "Vàng",
    bill: "311221CULVSHA2119959",
    bill_number: "R20211226001",
    shipping_terms: "CIF",
    gw: "65,066.13",
    pk: "928.0",
    import_or_export: "Nhập",
    mode_of_transport: "SEA",
    branch: "1",
    truck_type: "Cont40",
    truck_number: 5,
    factory_code: "ireier",
    dsk_person: null,
    check_person: null,
    note: "",
    fee: [
      {
        fee_id: "PHI01",
        fee_name: "Kiểm tra chất lượng đèn của bộ Khoa học Công nghệ",
        quantity: 1,
        unit_price: 13500000,
      },
      {
        fee_id: "PHI02",
        fee_name: "Test hiệu suất năng lượng",
        quantity: 1,
        unit_price: 5000000,
      },
    ],
  },
];

// export const SELECT_FEES: listFee[] = [
//   {
//     fee_id: "1",
//     fee_name: "Kiểm tra chất lượng đèn của bộ Khoa học Công nghệ",
//     quantity: 1,
//     unit_price: 13500000,
//   },
//   {
//     fee_id: "2",
//     fee_name: "Test hiệu suất năng lượng",
//     quantity: 1,
//     unit_price: 5000000,
//   },
// ];

export const OptionNv = [
  {
    value_nv: "nv01",
    label_nv: "Nguyễn Văn A",
    value_kh: "CÔNG TY TNHH SEOJIN VIỆT NAM 1",
    label_kh: "KH0011 - CÔNG TY TNHH SEOJIN VIỆT NAM 1",
  },
  {
    value_nv: "nv02",
    label_nv: "Nguyễn Văn U",
    value_kh: "CÔNG TY TNHH SEOJIN VIỆT NAM 2",
    label_kh: "KH0011 - CÔNG TY TNHH SEOJIN VIỆT NAM 2",
  },
  {
    value_nv: "nv03",
    label_nv: "Nguyễn Văn B",
    value_kh: "CÔNG TY TNHH SEOJIN VIỆT NAM 3",
    label_kh: "KH0011 - CÔNG TY TNHH SEOJIN VIỆT NAM 3",
  },
  {
    value_nv: "nv04",
    label_nv: "Nguyễn Văn C",
    value_kh: "CÔNG TY TNHH SEOJIN VIỆT NAM 2",
    label_kh: "KH0011 - CÔNG TY TNHH SEOJIN VIỆT NAM 2",
  },
  {
    value_nv: "nv05",
    label_nv: "Nguyễn Văn D",
    value_kh: "CÔNG TY TNHH SEOJIN VIỆT NAM 3",
    label_kh: "KH0011 - CÔNG TY TNHH SEOJIN VIỆT NAM 3",
  },
];
